//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBW2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBW2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon bukkit {
            get {
                object obj = ResourceManager.GetObject("bukkit", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxheap=1024M
        ///minheap=512M
        ///incgc=false
        ///jarpath=%ad%\craftbukkit.jar
        ///cburi=http://ci.bukkit.org/job/dev-CraftBukkit/Recommended/artifact/*zip*/archive.zip.
        /// </summary>
        internal static string DefaultConfig {
            get {
                return ResourceManager.GetString("DefaultConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled=false
        ///port=3000
        ///talkformat=say {1}.
        /// </summary>
        internal static string DefaultNetConfig {
            get {
                return ResourceManager.GetString("DefaultNetConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string DLWindow_button1_Click_Connecting___ {
            get {
                return ResourceManager.GetString("DLWindow_button1_Click_Connecting___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading file: .
        /// </summary>
        internal static string DLWindow_button1_Click_Error_downloading_file__ {
            get {
                return ResourceManager.GetString("DLWindow_button1_Click_Error_downloading_file__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error extracting file
        ///.
        /// </summary>
        internal static string DLWindow_DLWindow_ {
            get {
                return ResourceManager.GetString("DLWindow_DLWindow_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;&lt;cross-domain-policy&gt;&lt;allow-access-from domain=&quot;*&quot; to-ports=&quot;*&quot; /&gt;&lt;/cross-domain-policy&gt;.
        /// </summary>
        internal static string FlashAuthData {
            get {
                return ResourceManager.GetString("FlashAuthData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, the program was unable to find a compatible UPnP method and was unable to load automatic port forwarding. You will have to manually port forward.
        /// </summary>
        internal static string NO_UPNP {
            get {
                return ResourceManager.GetString("NO_UPNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is not running.
        /// </summary>
        internal static string ProcessHandler_Command_Server_is_not_running {
            get {
                return ResourceManager.GetString("ProcessHandler_Command_Server_is_not_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting server: .
        /// </summary>
        internal static string ProcessHandler_Start_Error_starting_server__ {
            get {
                return ResourceManager.GetString("ProcessHandler_Start_Error_starting_server__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing File.
        /// </summary>
        internal static string ProcessHandler_Start_Missing_File {
            get {
                return ResourceManager.GetString("ProcessHandler_Start_Missing_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The craftbukkit file was not found. Download it?.
        /// </summary>
        internal static string ProcessHandler_Start_The_craftbukkit_file_was_not_found__Download_it_ {
            get {
                return ResourceManager.GetString("ProcessHandler_Start_The_craftbukkit_file_was_not_found__Download_it_", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap restart {
            get {
                object obj = ResourceManager.GetObject("restart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap start {
            get {
                object obj = ResourceManager.GetObject("start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol must be specified. Accepted values are UPD or TCP..
        /// </summary>
        internal static string upnp_string1 {
            get {
                return ResourceManager.GetString("upnp_string1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Protocol. Accepted values are UPD or TCP..
        /// </summary>
        internal static string upnp_string2 {
            get {
                return ResourceManager.GetString("upnp_string2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Client must be specified..
        /// </summary>
        internal static string upnp_string3 {
            get {
                return ResourceManager.GetString("upnp_string3", resourceCulture);
            }
        }
    }
}
